name: Update GitHub Statistics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub statistics
        uses: cicirello/user-statistician@v1
        with:
          image-file: profile/github-stats.svg
          colors: dark-dimmed
          include-title: true
          custom-title: "GitHub Statistics"
          locale: en
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}